name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create ZIP with folder structure
        run: |
          mkdir package
          cp -r dist package/dist
          cp -r icons package/icons
          cd package
          zip -r ../lovelace-mushroomic-upstream.zip .

      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: lovelace-mushroomic-upstream.zip
